"""add tracks table and association

Revision ID: 7936d8184b9b
Revises: a4adc5b298fb
Create Date: 2022-10-09 00:45:51.659496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7936d8184b9b'
down_revision = 'a4adc5b298fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('album', sa.String(length=30), nullable=True),
    sa.Column('artist', sa.String(length=30), nullable=True),
    sa.Column('composer', sa.String(length=30), nullable=True),
    sa.Column('genre', sa.String(length=30), nullable=True),
    sa.Column('year', sa.String(length=30), nullable=True),
    sa.Column('audio_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url', sa.String(length=30), nullable=True),
    sa.Column('cover_url', sa.String(length=30), nullable=True),
    sa.Column('created_data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_associations',
    sa.Column('playlist_id', postgresql.UUID(), nullable=False),
    sa.Column('track_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_associations')
    op.drop_table('tracks')
    # ### end Alembic commands ###
